# λ █                                

format = '''
[](bg:#282a36 fg:#ff5555)[](bg:#6272a4 fg:#ff5555)[⌈$directory⌋](bg:#6272a4 fg:#f8f8f2)[](bg:#6272a4 fg:#8be9fd)$git_branch[](bg:#8be9fc fg:#282a36)[](bg:#282a36 fg:#8be9fd)
[  ╰](bg:#282a36 fg:#f8f8f2)[](bg:#bd93f9 fg:#282a36)[ $character ](bg:#bd93f9 fg:#f8f8f2)[](bg:#282a36 fg:#bd93f9) '''

right_format = '''
[]()$time $username[@](fg:#ff92df)$hostname[]()'''

[directory]
disabled = false
format = "[$path](bg:#6272a4 fg:#f8f8f2)"

[character]
disabled = false
format = "$symbol"
success_symbol = "[λ](bg:#bd93f9 fg:#50fa7b)"
error_symbol = "[χ](bg:#bd93f9 fg:#ff5555)"

[time]
disabled = false
format = "[$time](bg:# fg:#)"
time_format = "%H:%M%a%e %b %Y"

[username]
disabled = false
show_always = true
format = "[$user](bg:# fg:#)"

[hostname]
disabled = false
ssh_only = false
format = "[$hostname](bg:# fg:#)"

[git_branch]
disabled = false
always_show_remote = true
format = "[](bg:#ff79c6 fg:#8be9fd)[$remote_name >>> $symbol$branch](bg:#ff79c6 fg:#21222c)[](bg:#8be9fd fg:#ff79c6)"
symbol = ""

