#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap ch &
xrandr -s 1280x720 &
pkill picom
picom &
~/.config/polybar/launch.sh
xrdb -load .Xresources &
xterm -e fish &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 1
bspc config window_gap 1

bspc config split_ratio 0.5

bspc config normal_border_color "#666666"
bspc config focused_border_color "#ffffff"
