#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap ch &
xrandr -s 1280x720 &
xrdb -load .Xresources
~/.fehbg &
pkill picom
picom &
~/.config/polybar/launch.sh
xterm -e fish &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 1
bspc config window_gap 1

bspc config split_ratio 0.5

bspc config normal_border_color "#777777"
bspc config focused_border_color "#ffffff"
